from __future__ import annotations


class Identifier:
    @property
    def value(self) -> str: ...
    def __getstate__(self) -> str: ...
    def __setstate__(self, state: str) -> None: ...
    def __lt__(self, other: Identifier) -> bool: ...
    def __le__(self, other: Identifier) -> bool: ...
    def __gt__(self, other: Identifier) -> bool: ...
    def __ge__(self, other: Identifier) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...


class TraderId(Identifier):
    def __init__(self, value: str) -> None: ...
    def __getstate__(self) -> str: ...
    def __setstate__(self, state: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def get_tag(self) -> str: ...


class ComponentId(Identifier):
    def __init__(self, value: str) -> None: ...
    def __getstate__(self) -> str: ...
    def __setstate__(self, state: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
